networks:
  default:
    driver: bridge

services:
  explorer:
    container_name: ltc-rpc-explorer
    #define $UID, $GID in .env file the user to run docker and write in data folder
    #user: "1000:1000"
    environment:
      LTCEXP_HOST: 0.0.0.0
      LTCEXP_LITECOIND_URI: $LTCEXP_LITECOIND_URI
      LTCEXP_ADDRESS_API: $LTCEXP_ADDRESS_API
      LTCEXP_ELECTRUM_SERVERS: $LTCEXP_ELECTRUM_SERVERS
      LTCEXP_SLOW_DEVICE_MODE: false
      #More information mode, including Litecoin exchange rates
      #More privacy mode, no external queries
      # LTCEXP_PRIVACY_MODE: true
      # LTCEXP_NO_RATES: true
      # LTCEXP_UI_THEME: dark
    build:
      context: ./
    image: ltc-rpc-explorer:latest
    #restart: "no"
    ports:
      - "3003:3003"
